### ISSUE TITLE
the minimap issue

### ISSUE THREAD

**Issue by shotaro7906** [lastbattle/Harepacker-resurrected#100]
hi, it seems the minimap issue be fixed following changing 5 days ago? I use the latest  release version in October 2020 and fount that I cannot go to the map otherwise the client will close and I found the reason is the minimap in wz. So I delete minimap then I can go to the new map.  Idk how to fix this problem, QaQ just lookning for help !! many thanks !!!

**Comment by lastbattle** [comment]
Yes its fixed, but I have yet to make a new release pending other unresolved issues.
