### ISSUE TITLE
Negative value is not valid

### ISSUE THREAD

**Issue by TokyoSU** [lastbattle/Harepacker-resurrected#102]
hello, sorry to disturb you again but as you can see here: https://i.imgur.com/Pq01DwU.png
the negative at the right (image) is just shifted to positive (maybe a uint ?) and at the left (image) it's the right value (int).
it's really boring to convert it to json to get the right value, why anyone don't reported that faster ?
please can you fix it ? :)

PS: im using the staging version, if  it can help.
PS2: after a closer look, all value that are negative in the .wz is just shifted to position in harepacker :x

**Comment by lastbattle** [comment]
https://github.com/lastbattle/Harepacker-resurrected/commit/5057b717a0f46cc7db63a1f67122ebd57860d728

fixed

**Comment by TokyoSU** [comment]
Work like a charm thank you :D
