### ISSUE TITLE
image error 

### ISSUE THREAD

**Issue by kikimonkey** [lastbattle/Harepacker-resurrected#107]
build last commit code, all images show error.

이 대화 상자 대신 JIT(Just-in-time) 디버깅을 호출하는
방법에 대한 자세한 내용은 이 메시지의 뒷부분을 참조하십시오.

************** 예외 텍스트 **************
System.IO.FileLoadException: 파일이나 어셈블리 'SharpDX.DXGI, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b4dcf0f35e5521f1' 또는 여기에 종속되어 있는 파일이나 어셈블리 중 하나를 로드할 수 없습니다. 찾은 어셈블리의 매니페스트 정의와 어셈블리 참조가 일치하지 않습니다. (예외가 발생한 HRESULT: 0x80131040)
파일 이름: 'SharpDX.DXGI, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b4dcf0f35e5521f1' ---> System.IO.FileLoadException: 파일이나 어셈블리 'SharpDX.DXGI, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b4dcf0f35e5521f1' 또는 여기에 종속되어 있는 파일이나 어셈블리 중 하나를 로드할 수 없습니다. 찾은 어셈블리의 매니페스트 정의와 어셈블리 참조가 일치하지 않습니다. (예외가 발생한 HRESULT: 0x80131040)
파일 이름: 'SharpDX.DXGI, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b4dcf0f35e5521f1'

경고: 어셈블리 바인딩 로깅이 꺼져 있습니다.
어셈블리 바인딩 오류 로깅 기능을 사용하려면 레지스트리 값 [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD)를 1로 설정하십시오.
참고: 어셈블리 바인딩 오류 로깅 기능을 사용하도록 설정하면 그렇지 않은 경우보다 성능이 약간 떨어집니다.
이 기능을 끄려면 레지스트리 값 [HKLM\Software\Microsoft\Fusion!EnableLog]를 제거하십시오.

   위치: System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   위치: System.Reflection.RuntimeMethodInfo.FetchNonReturnParameters()
   위치: System.Reflection.RuntimeMethodInfo.GetParameters()
   위치: System.Diagnostics.StackTrace.ToString(TraceFormat traceFormat)
   위치: System.Exception.GetStackTrace(Boolean needFileInfo)
   위치: System.IO.FileLoadException.ToString()
   위치: System.Windows.Forms.ThreadExceptionDialog..ctor(Exception t)
   위치: System.Windows.Forms.Application.ThreadContext.OnThreadException(Exception t)
   위치: System.Windows.Forms.Control.WndProcException(Exception e)
   위치: System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   위치: System.Windows.Forms.UnsafeNativeMethods.SendMessage(HandleRef hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   위치: System.Windows.Forms.Control.SendMessage(Int32 msg, IntPtr wparam, IntPtr lparam)
   위치: System.Windows.Forms.Control.ReflectMessageInternal(IntPtr hWnd, Message& m)
   위치: System.Windows.Forms.Control.WmNotify(Message& m)
   위치: System.Windows.Forms.Control.WndProc(Message& m)
   위치: System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** 로드된 어셈블리 **************
mscorlib
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4300.0 built by: NET48REL1LAST_C
    코드베이스: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
HaRepackerResurrected
    어셈블리 버전: 4.2.4.0
    Win32 버전: 4.2.4.0
    코드베이스: file:///C:/Users/A/Desktop/%EC%83%88%20%ED%8F%B4%EB%8D%94/Harepacker-resurrected-master/Harepacker-resurrected-master/Compiled/Debug/AnyCPU/HaRepackerResurrected.exe
----------------------------------------
MapleLib
    어셈블리 버전: 2.0.0.0
    Win32 버전: 2.0.0.0
    코드베이스: file:///C:/Users/A/Desktop/%EC%83%88%20%ED%8F%B4%EB%8D%94/Harepacker-resurrected-master/Harepacker-resurrected-master/Compiled/Debug/AnyCPU/MapleLib.DLL
----------------------------------------
System.Drawing
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4084.0 built by: NET48REL1
    코드베이스: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4300.0 built by: NET48REL1LAST_C
    코드베이스: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4270.0 built by: NET48REL1LAST_C
    코드베이스: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
Newtonsoft.Json
    어셈블리 버전: 12.0.0.0
    Win32 버전: 12.0.3.23909
    코드베이스: file:///C:/Users/A/Desktop/%EC%83%88%20%ED%8F%B4%EB%8D%94/Harepacker-resurrected-master/Harepacker-resurrected-master/Compiled/Debug/AnyCPU/Newtonsoft.Json.DLL
----------------------------------------
System.Core
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4320.0 built by: NET48REL1LAST_C
    코드베이스: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Numerics
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4084.0 built by: NET48REL1
    코드베이스: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4250.0 built by: NET48REL1LAST_C
    코드베이스: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4270.0 built by: NET48REL1LAST_C
    코드베이스: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Xml
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4084.0 built by: NET48REL1
    코드베이스: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
PresentationFramework
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4320.0
    코드베이스: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
WindowsBase
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4320.0 built by: NET48REL1LAST_C
    코드베이스: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
PresentationCore
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4320.0 built by: NET48REL1LAST_C
    코드베이스: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
System.Xaml
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4320.0 built by: NET48REL1LAST_C
    코드베이스: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
System.Configuration
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4190.0 built by: NET48REL1LAST_B
    코드베이스: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
HaRepackerResurrected.resources
    어셈블리 버전: 4.2.4.0
    Win32 버전: 4.2.4.0
    코드베이스: file:///C:/Users/A/Desktop/%EC%83%88%20%ED%8F%B4%EB%8D%94/Harepacker-resurrected-master/Harepacker-resurrected-master/Compiled/Debug/AnyCPU/ko/HaRepackerResurrected.resources.DLL
----------------------------------------
mscorlib.resources
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4084.0 built by: NET48REL1
    코드베이스: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_ko_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
WindowsFormsIntegration
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4084.0 built by: NET48REL1
    코드베이스: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/WindowsFormsIntegration/v4.0_4.0.0.0__31bf3856ad364e35/WindowsFormsIntegration.dll
----------------------------------------
HaSharedLibrary
    어셈블리 버전: 1.0.0.0
    Win32 버전: 1.0.0.0
    코드베이스: file:///C:/Users/A/Desktop/%EC%83%88%20%ED%8F%B4%EB%8D%94/Harepacker-resurrected-master/Harepacker-resurrected-master/Compiled/Debug/AnyCPU/HaSharedLibrary.DLL
----------------------------------------
PresentationFramework.Aero2
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4084.0 built by: NET48REL1
    코드베이스: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework.Aero2/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.Aero2.dll
----------------------------------------
PresentationFramework.resources
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4084.0
    코드베이스: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework.resources/v4.0_4.0.0.0_ko_31bf3856ad364e35/PresentationFramework.resources.dll
----------------------------------------
ICSharpCode.AvalonEdit
    어셈블리 버전: 6.0.1.278
    Win32 버전: 6.0.1.278
    코드베이스: file:///C:/Users/A/Desktop/%EC%83%88%20%ED%8F%B4%EB%8D%94/Harepacker-resurrected-master/Harepacker-resurrected-master/Compiled/Debug/AnyCPU/ICSharpCode.AvalonEdit.DLL
----------------------------------------
PresentationCore.resources
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4084.0 built by: NET48REL1
    코드베이스: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationCore.resources/v4.0_4.0.0.0_ko_31bf3856ad364e35/PresentationCore.resources.dll
----------------------------------------
WpfAnimatedGif
    어셈블리 버전: 2.0.0.0
    Win32 버전: 2.0.0.0
    코드베이스: file:///C:/Users/A/Desktop/%EC%83%88%20%ED%8F%B4%EB%8D%94/Harepacker-resurrected-master/Harepacker-resurrected-master/Compiled/Debug/AnyCPU/WpfAnimatedGif.DLL
----------------------------------------
PresentationFramework-SystemXml
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4084.0
    코드베이스: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemXml/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemXml.dll
----------------------------------------
PresentationFramework-SystemData
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4320.0
    코드베이스: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemData/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemData.dll
----------------------------------------
UIAutomationTypes
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4320.0 built by: NET48REL1LAST_C
    코드베이스: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/UIAutomationTypes/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationTypes.dll
----------------------------------------
UIAutomationProvider
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4320.0 built by: NET48REL1LAST_C
    코드베이스: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/UIAutomationProvider/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationProvider.dll
----------------------------------------
Accessibility
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4084.0 built by: NET48REL1
    코드베이스: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
MonoGame.Framework
    어셈블리 버전: 3.8.0.1641
    Win32 버전: 3.8.0.1641
    코드베이스: file:///C:/Users/A/Desktop/%EC%83%88%20%ED%8F%B4%EB%8D%94/Harepacker-resurrected-master/Harepacker-resurrected-master/Compiled/Debug/AnyCPU/MonoGame.Framework.DLL
----------------------------------------
System.Windows.Forms.resources
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4084.0 built by: NET48REL1
    코드베이스: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_ko_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** JIT 디버깅 **************
JIT(Just In Time) 디버깅을 사용하려면 이 응용 프로그램 또는 컴퓨터의
config 파일(machine.config)의 jitDebugging 값을 
system.windows.forms 섹션에 설정해야 합니다.
또한 응용 프로그램은 디버깅할 수 있도록 컴파일되어야
합니다.

예:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

JIT 디버깅을 사용하면 처리되지 않은 모든 예외는
이 대화 상자에서 처리되지 않고 컴퓨터에 등록된 JIT 
디버거에 보내집니다.

**Comment by lastbattle** [comment]
It's fixed.

https://github.com/lastbattle/Harepacker-resurrected/commit/d89dbfa1d08ea344d884ddd707e168fb834bffe9
