### ISSUE TITLE
Change Image

### ISSUE THREAD

**Issue by Atoot** [lastbattle/Harepacker-resurrected#108]
![_{DG1%HM$5@~UJYB$1IP1OY](https://user-images.githubusercontent.com/26664343/108479369-9dbb6480-72d0-11eb-88c3-234df1f0a118.png)
![_MH K1OW28Z@S) NDVIXLJO](https://user-images.githubusercontent.com/26664343/108479377-a01dbe80-72d0-11eb-8b5c-fbeb819cb719.png)
Save after changing the image, when I open it again. Image is gone.

**Comment by Atoot** [comment]
Cannot save the changed image correctly.

**Comment by lastbattle** [comment]
This has already been fixed, but I've yet to make a new release for that.
If you need it right now, you should compile it yourself.
