### ISSUE TITLE
GMS v0.35 compatibility

### ISSUE THREAD

**Issue by jvdnbus** [lastbattle/Harepacker-resurrected#11]
Do you think it's possible to add support for such old versions? Right now, it just loads in a bunch of unreadable names.

Top is v35, bottom is v62 I reckon:
![](https://i.imgur.com/Ot7jp4o.png)

**Comment by Arnuh** [comment]
Can you provide a download for v35 files?

**Comment by jvdnbus** [comment]
https://mega.nz/#!FPhUUaYY!fMoH3GOCln7iRzNbPfZBR8OHkBqy4Eq4xqshtxvGWzE

**Comment by shavitush** [comment]
the irony in this issue is real

![image](https://user-images.githubusercontent.com/3672466/74202478-33132a00-4c75-11ea-99ef-b4a625f2bb7a.png)

**Comment by Arnuh** [comment]
Well these aren't v35 files. They are v38 from MY private server and I can confirm they load just fine. I assume you're using GMS(old) instead of BMS.

Also good chance anything you do will be caught.

**Comment by jvdnbus** [comment]
Haha, the odds! I don't actually play the private server but I wanted to try and develop my own old version. Thanks.

**Comment by lastbattle** [comment]
Great that it works! Closed. 
Let me know if you need anything else, feel free to just open another thread.
