### ISSUE TITLE
hacreator error

### ISSUE THREAD

**Issue by kikimonkey** [lastbattle/Harepacker-resurrected#113]
https://youtu.be/FMNIKdBKqtE

tap close error & edit map info does not apply

**Comment by lastbattle** [comment]
Partially fixed, the header of the tab is now updated accordingly.
https://github.com/lastbattle/Harepacker-resurrected/commit/090d53ce9b2f2af98ae5c52802697d26de41f1d8

Will look at the other issue of closing the main tab when I have more time to spare.

**Comment by lastbattle** [comment]
Fixed.
https://github.com/lastbattle/Harepacker-resurrected/commit/5abb50c90558193effc14d3f8d084a952b0be45d
