### ISSUE TITLE
PNG extraction fails on small images

### ISSUE THREAD

**Issue by ifSomeday** [lastbattle/Harepacker-resurrected#117]
Extracting small images results in a broken png file with no actual data beyond the basic png structure.

I noticed when trying to export the following files to png:
`UI.wz/UIWindow2.img/Kite/Ranking/NumRank/*`
`UI.wz/UIWindow2.img/Kite/Result/NumRank/*`
`UI.wz/UIWindow2.img/Kite/Result/NumPoint/*`

I'm not sure if the image size is the culprit, but all these failed extractions were for imagines <25x25 pixels, while the larger images in the same directories extracted fine.

This was observed on 292b966c

**Comment by lastbattle** [comment]
https://github.com/lastbattle/Harepacker-resurrected/issues/119

Could be related, its resolved.
