### ISSUE TITLE
I can't activate it anymore.

### ISSUE THREAD

**Issue by nuts670** [lastbattle/Harepacker-resurrected#118]
I can't start it anymore. Probably after the windows update, I can't boot anymore.
How do I get it to start?

Just-In-Time (JIT) デバッグを呼び出すための詳細については、
ダイアログ ボックスではなく、このメッセージの最後を参照してください。
(For more information on invoking Just-In-Time (JIT) debugging, please refer to the end of this message instead of the
See the end of this message, not the dialog box.)

************** 例外テキスト **************
System.NullReferenceException: オブジェクト参照がオブジェクト インスタンスに設定されていません。
   場所 HaRepacker.Program.PrepareApplication(Boolean from_internal) 場所 D:\Git\Harepacker-resurrected\HaRepacker\Program.cs:行 162
   場所 HaRepacker.Program.Main(String[] args) 場所 D:\Git\Harepacker-resurrected\HaRepacker\Program.cs:行 65
(System.NullReferenceException: Object reference not set to object instance.
   PrepareApplication(Boolean from_internal) Location D:\Git\Harepacker-resurrected\HaRepacker\Program.cs:line 162
   Program.Main(String[] args) place D:\Git\Harepacker-resurrected\HaRepacker\Program.cs:line 65)

************** 読み込まれたアセンブリ **************
mscorlib
    アセンブリ バージョン:4.0.0.0
    Win32 バージョン:4.8.4300.0 built by: NET48REL1LAST_C
    コードベース:file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
HaRepackerResurrected
    アセンブリ バージョン:4.2.4.0
    Win32 バージョン:4.2.4.0
    コードベース:file:///C:/Users/ndaba/OneDrive/%E3%83%87%E3%82%B9%E3%82%AF%E3%83%88%E3%83%83%E3%83%97/maple%E9%96%A2%E4%BF%82/Maple%20Eden/x86/HaRepackerResurrected.exe
----------------------------------------
System.Windows.Forms
    アセンブリ バージョン:4.0.0.0
    Win32 バージョン:4.8.4270.0 built by: NET48REL1LAST_C
    コードベース:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    アセンブリ バージョン:4.0.0.0
    Win32 バージョン:4.8.4300.0 built by: NET48REL1LAST_C
    コードベース:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    アセンブリ バージョン:4.0.0.0
    Win32 バージョン:4.8.4084.0 built by: NET48REL1
    コードベース:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
MapleLib
    アセンブリ バージョン:2.0.0.0
    Win32 バージョン:2.0.0.0
    コードベース:file:///C:/Users/ndaba/OneDrive/%E3%83%87%E3%82%B9%E3%82%AF%E3%83%88%E3%83%83%E3%83%97/maple%E9%96%A2%E4%BF%82/Maple%20Eden/x86/MapleLib.DLL
----------------------------------------
Newtonsoft.Json
    アセンブリ バージョン:12.0.0.0
    Win32 バージョン:12.0.3.23909
    コードベース:file:///C:/Users/ndaba/OneDrive/%E3%83%87%E3%82%B9%E3%82%AF%E3%83%88%E3%83%83%E3%83%97/maple%E9%96%A2%E4%BF%82/Maple%20Eden/x86/Newtonsoft.Json.DLL
----------------------------------------
System.Core
    アセンブリ バージョン:4.0.0.0
    Win32 バージョン:4.8.4320.0 built by: NET48REL1LAST_C
    コードベース:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Numerics
    アセンブリ バージョン:4.0.0.0
    Win32 バージョン:4.8.4084.0 built by: NET48REL1
    コードベース:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    アセンブリ バージョン:4.0.0.0
    Win32 バージョン:4.8.4250.0 built by: NET48REL1LAST_C
    コードベース:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    アセンブリ バージョン:4.0.0.0
    Win32 バージョン:4.8.4270.0 built by: NET48REL1LAST_C
    コードベース:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Xml
    アセンブリ バージョン:4.0.0.0
    Win32 バージョン:4.8.4084.0 built by: NET48REL1
    コードベース:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
mscorlib.resources
    アセンブリ バージョン:4.0.0.0
    Win32 バージョン:4.8.4084.0 built by: NET48REL1
    コードベース:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_ja_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Configuration
    アセンブリ バージョン:4.0.0.0
    Win32 バージョン:4.8.4190.0 built by: NET48REL1LAST_B
    コードベース:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Windows.Forms.resources
    アセンブリ バージョン:4.0.0.0
    Win32 バージョン:4.8.4084.0 built by: NET48REL1
    コードベース:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_ja_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** JIT デバッグ **************
Just-In-Time (JIT) デバッグを有効にするには、このアプリケーション、
またはコンピューター (machine.config) の構成ファイルの jitDebugging 
値を system.windows.forms セクションで設定しなければなりません。
アプリケーションはまた、デバッグを有効にしてコンパイルされなければ
なりません。

例:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

JIT デバッグが有効なときは、このダイアログ ボックスで処理するよりも、
ハンドルされていない例外はすべてコンピューターに登録された
JIT デバッガーに設定されなければなりません。

**Comment by lastbattle** [comment]
C:\Users\<User>\AppData\Roaming\HaRepacker

Delete the folder, and you should be able to open it once again. I'll look into fixing it.

**Comment by nuts670** [comment]
It's working. Thank you.

**Comment by lastbattle** [comment]
😃 👌👌
