### ISSUE TITLE
Most of the pictures exported by Character.wz fail

### ISSUE THREAD

**Issue by boynton89** [lastbattle/Harepacker-resurrected#119]
Most of the pictures exported by Character.wz fail
Most pictures don’t show up
It is normal to save one by one manually

**Comment by boynton89** [comment]
![image](https://user-images.githubusercontent.com/31771497/116344400-be47f380-a818-11eb-87f1-cfca54035b76.png)
as the picture shows

**Comment by lastbattle** [comment]
I'll take a second look at it

**Comment by lastbattle** [comment]
Its fixed. 80f1d64aff3e980292a52633915f917a7dc98c0b
As I might not be making a new release any time soon, you might want to compile HaRepacker yourself.
