### ISSUE TITLE
Harepacker-resurrected does not compile when initially cloned

### ISSUE THREAD

**Issue by mechpaul** [lastbattle/Harepacker-resurrected#12]
To reproduce the error:
(1) Git clone a fresh repository
(2) compile it

My VSCommunity 2017 had several complaints about it. It complained about files in Harepacker-resurrected/Spine that didn't exist:

https://github.com/lastbattle/Harepacker-resurrected/blob/172315f78fa3e2504bc31decfbcdec00ce77ece8/HaRepacker/Harepacker-resurrected.csproj#L373

Then there's also the requirement to install the DockPanel suite which is not documented anywhere.

Can someone create a compile guide of all requirements? I'm too scared to run down dependency hell to get this thing to compile.

**Comment by lastbattle** [comment]
It should be fixed by now. 
I have just tested with a clean clone of the repo along with VS 2019, and it compiles fine right out of the box.

https://github.com/lastbattle/Harepacker-resurrected/commit/e68677820486faefb880cd98c65da8a50d79e4e8

**Comment by mechpaul** [comment]
Aha, just tested this again. I tried to recompile it and it failed. I changed the startup project to Harepacker-resurrected and it works.
