### ISSUE TITLE
HaCreator | mapStringParent was null

### ISSUE THREAD

**Issue by VirtualDylan** [lastbattle/Harepacker-resurrected#124]
Fairly new to a lot of this.. could be doing something wrong but here is what I am running into:

![image](https://user-images.githubusercontent.com/39929837/121828875-ed160e00-cc8e-11eb-8755-d9a5bc1a4442.png)

![image](https://user-images.githubusercontent.com/39929837/121828889-f7380c80-cc8e-11eb-97d9-b43f95e87db6.png)

System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=HaCreator
  StackTrace:
   at HaCreator.Wz.WzFileManager.ExtractStringWzMaps() in C:\Users\User\Desktop\HaDEV\Harepacker-resurrected\HaCreator\Wz\WzFileManager.cs:line 332

**Comment by VirtualDylan** [comment]
User-error -- when using 'Auto-Detect' for the encryption I get the above error. 
![image](https://user-images.githubusercontent.com/39929837/121832723-b93fe600-cc98-11eb-980c-a1159ec1ee07.png)

Changing it to GMS seems to work

**Comment by lastbattle** [comment]
Use 'GMS' instead of 'Auto-Detect, as it might not possibility work sometimes.
