### ISSUE TITLE
Tell me how to open the hacreator.

### ISSUE THREAD

**Issue by wnsgh3015** [lastbattle/Harepacker-resurrected#127]
Hello, I am Korean.
I have to use the hacreator urgently because I need to modify the map.
I don't know how to open it, so I've searched everywhere, but I can't
I've built it into Visual Studio 2019.
Could not open due to an error.
Can anyone tell me how to build it in detail?

**Comment by lastbattle** [comment]
All you need to install is just MS Visual Studio 2019. 
And run 'MapleHaSuite.sln'

**Comment by wnsgh3015** [comment]
I'm doing that, but there's an error.

**Comment by wnsgh3015** [comment]
Once it's done, there's an error. "Object reference is not set to an instance of an object"
