### ISSUE TITLE
New KMST patch format causes HaRepacker to fail on opening

### ISSUE THREAD

**Issue by mechpaul** [lastbattle/Harepacker-resurrected#136]
This is a minor bug that could be fixed easily, I think.

http://www.southperry.net/showthread.php?t=83232&p=1323867&viewfull=1#post1323867

The issue is with the base "Base.wz" file (or Skill.wz or Effect.wz or whatever)

[Base.zip](https://github.com/lastbattle/Harepacker-resurrected/files/7177759/Base.zip)

If you try to open Base.wz here, HaRepacker fails because it tries to compute an offset for this wz file, and there are no offsets or files here. So if the wz file contains no .img/.lua files within it, don't compute anything because there's no data here.

Why did Nexon choose this format? No clue. But they did.

**Comment by lastbattle** [comment]
Noted, will be adding support for the new split wz format in a bit too..

**Comment by lastbattle** [comment]
https://github.com/lastbattle/Harepacker-resurrected/commit/63e2d72ac006f0a45fc324a2c33c23f0a4a988fa

Just a few more steps 🤔

**Comment by superboas** [comment]
> sorry. posted a new thread regarding the same issue. seems like the new msea v212 wz files cant be opened too. want to check if its due to the same issue or different format?

its been solved. could you drop me a message @ qwertgs#5869 on disc i'll help you solve it. also have some questions of my own, hoping you can help

**Comment by superboas** [comment]
> sorry. posted a new thread regarding the same issue. seems like the new msea v212 wz files cant be opened too. want to check if its due to the same issue or different format?

believed its been fixed. drop me a message on disc superboas#4736 i can help you with it. also have a few questions hopefully you can help me too

**Comment by orayneo1984** [comment]
> > sorry. posted a new thread regarding the same issue. seems like the new msea v212 wz files cant be opened too. want to check if its due to the same issue or different format?
> 
> believed its been fixed. drop me a message on disc superboas#4736 i can help you with it. also have a few questions hopefully you can help me too

Seems like maple client scan game files now, any edit on wz will crashed the game instantly, correct me if wrong. Thanks

**Comment by superboas** [comment]
> > > sorry. posted a new thread regarding the same issue. seems like the new msea v212 wz files cant be opened too. want to check if its due to the same issue or different format?
> > 
> > 
> > believed its been fixed. drop me a message on disc superboas#4736 i can help you with it. also have a few questions hopefully you can help me too
> 
> Seems like maple client scan game files now, any edit on wz will crashed the game instantly, correct me if wrong. Thanks

im no expert on this but I managed to make a few edits without crashing the game (can't say for sure whether there will be delay ban though) but yea as you said many of the previous edits that used to work seem to crash the game

**Comment by iemmsam** [comment]
> superboas#4736

hi sent in discord

**Comment by itshou** [comment]
SAME HERE.... any solution to make it work ?  disc Itshou#6476

**Comment by Ermmmmmmmm** [comment]
> > > > sorry. posted a new thread regarding the same issue. seems like the new msea v212 wz files cant be opened too. want to check if its due to the same issue or different format?
> > > 
> > > 
> > > believed its been fixed. drop me a message on disc superboas#4736 i can help you with it. also have a few questions hopefully you can help me too
> > 
> > 
> > Seems like maple client scan game files now, any edit on wz will crashed the game instantly, correct me if wrong. Thanks
> 
> im no expert on this but I managed to make a few edits without crashing the game (can't say for sure whether there will be delay ban though) but yea as you said many of the previous edits that used to work seem to crash the game

Hello bro, which version of harepacker you are using for editing v212? I can't find a working version with it.

**Comment by lastbattle** [comment]
Fixed. Thanks! 63e2d72ac006f0a45fc324a2c33c23f0a4a988fa

Available in the new release https://github.com/lastbattle/Harepacker-resurrected/releases/tag/5.0
