### ISSUE TITLE
Game Version Hash Error

### ISSUE THREAD

**Issue by onblack6** [lastbattle/Harepacker-resurrected#151]
Having some issues saving a wz file with a custom encryption key, receiving the following error:

![image](http://puu.sh/IhIkr/c4bfd54187.png)

File & keys here:
[https://drive.google.com/file/d/1_O9_5sPcoONN65JBWAKNGqeHNsqIGpNj/view?usp=sharing](url)

**Comment by lastbattle** [comment]
Its fixed here https://github.com/lastbattle/Harepacker-resurrected/commit/60fa3818774125af21dc492553ed1a5a389b451c. 
You'll have to compile it yourself for now as I'll not be making a new release yet.
