### ISSUE TITLE
can't open file 

### ISSUE THREAD

**Issue by stillLanze** [lastbattle/Harepacker-resurrected#153]
<font class="papago-parent"><font class="papago-source" style="display:none;">Sorry.
</font>미안하다
</font><font class="papago-parent"><font class="papago-source" style="display:none;">I can't speak English, so I'm translating
</font>나는 영어를 할 줄 몰라서 번역하는 중이야.
</font><font class="papago-parent"><font class="papago-source" style="display:none;">can't open file ㅠㅠ 
</font>파일 ㅠㅠ을 열 수 없음 
</font><font class="papago-parent"><font class="papago-source" style="display:none;">In KMS, it cannot be opened because an error has occurred as shown in the figure below.
</font>KMS에서 아래 그림과 같이 에러가 발생하여 열 수 없다.</font><font class="papago-parent"><font class="papago-source" style="display:none;"> 
</font> 
 
</font><font class="papago-parent"><font class="papago-source" style="display:none;">Because of the language wall, I'm writing here
</font>언어벽 때문에 여기에 글을 쓴다.
</font><font class="papago-parent"><font class="papago-source" style="display:none;">I'm trying hard to find a solution 
</font>나는 해결책을 찾기 위해 열심히 노력하고 있다. 
</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>

</font>![화면 캡처 2021-12-11 172212](https://user-images.githubusercontent.com/95957902/145669836-4a0dcd2f-e5ee-4e9f-b450-c7e7140c9ae4.png)
</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>

</font><font class="papago-parent"><font class="papago-source" style="display:none;">But check that you can open the file in  WzComparerR2
</font>그러나 WzCompareR2에서 파일을 열 수 있는지 확인하십시오.
</font><font class="papago-parent"><font class="papago-source" style="display:none;">![화면 캡처 2021-12-11 1728141](https://user-images.githubusercontent.com/95957902/145670021-b36099c9-318f-43fd-a824-ec10a2ff0383.png)

</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>

</font><font class="papago-parent"><font class="papago-source" style="display:none;">It doesn't seem to open because the file selection in the red circle is different.</font>빨간 원 안의 파일 선택이 달라서 열리지 않는 것 같다.</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>

</font><font class="papago-parent"><font class="papago-source" style="display:none;">when i doubt
</font>의심스럽지만
</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>

</font><font class="papago-parent"><font class="papago-source" style="display:none;">If you know of any other workaround, please let me know.</font>다른 해결 방법을 알고 있다면 알려줘.</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>

</font>

**Comment by stillLanze** [comment]
만약 한국인 분이 이걸해결가능하신분있다면 제발 부디 알려주세요  kms에서 파일을 열 수 없어 울고 있는 중 ㅠㅠ.

**Comment by leesumin1** [comment]
저도 이것때메 골 아픈데 혹시 해결 하셨나요 ? 연락처 좀 주세여

**Comment by stillLanze** [comment]
> 저도 이것때메 골 아픈데 혹시 해결 하셨나요 ? 연락처 좀 주세여저도 이것때메 골 아픈데 혹시 해결 하셨나요 ? 연락처 좀 주세여

아직 아무것도 해결책을 찾지못했어요. ㅠㅠ

**Comment by stillLanze** [comment]
Nothing worked, but I don't know what to do...
Only KMS is not working
If you know a solution or have solved it, please let me know the procedure.
Necessary items, etc.
I've tried this, but it still doesn't work ㅠㅠ

**Comment by stillLanze** [comment]
Nothing has been resolved yet and I don't know what to do
I also downloaded the preparations and tried downloading this and that
didn't work out
If you know a way to fix it, show me the processㅠㅠ

**Comment by lastbattle** [comment]
Hi, I will update it as soon as I have some time to spare.
The latest KMS update changed the WZ encoding a little.

https://forum.ragezone.com/f702/release-harepacker-resurrected-1149521/index11.html#post9107015

**Comment by stillLanze** [comment]
soooooooooooooooooooooooooo thank you.
26th next patch in Destiny
If you can't open the file after receiving the patch then
I'll be back

**Comment by lastbattle** [comment]
I'm working at it right now, just got the new KMS installation. Will make an intermediate release in a bit.

**Comment by stillLanze** [comment]
hooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooou
Really really really berry thank you so much
to bother you so muchSorry
Take care of your health
late but merry christmas
![da238dc3a982fa7dfa89055279f8fe96](https://user-images.githubusercontent.com/95957902/147518921-34349b2c-f7a9-4fe5-b3e5-26b7b90292b1.jpg)

**Comment by lastbattle** [comment]
![image](https://user-images.githubusercontent.com/4586194/147535836-1eef317c-4114-40a8-8e19-437feba44f1b.png)

Done.
Just some more testing to ensure that I dont break compatibility with old WZ files.

**Comment by stillLanze** [comment]
it was run
hooooooooooooooooooooooooooooooooooooooooooooooou
![image](https://user-images.githubusercontent.com/95957902/147558041-3b860751-6173-4eb5-bf19-ec98a371b609.png)

**Comment by leesumin1** [comment]
테섭에서 또 안열리는데 개발자 한테 확인 해달라고 말 해주실 수 있나요?

**Comment by stillLanze** [comment]
woooo bro......
like the text above 
The test server file is
not open
![image](https://user-images.githubusercontent.com/95957902/147578446-30bb8b13-d296-415c-a584-47bdfa6fd31c.png)

Otherwise, we'll have to wait until the 12/30th.
after patch 
report the situation
like an error message
MapleStory It opens regardless of when I open the file inside.
The same error occurs only when I move other files to another file and open the file.
![image](https://user-images.githubusercontent.com/95957902/147578936-9b8e4616-b295-4a37-934d-992d57b066f7.png)
Dammmm

**Comment by stillLanze** [comment]
+There's a problem. The reason I use Haripeker is to change the BGM and apply it to MapleStory. 
After changing the BGM Save it and run MapleStory.
The saved file is treated as a missing file and the game is run. 
*uck
help!!
Sorry to bother you once more

**Comment by stillLanze** [comment]
+additional saved files but not applicable
You can open the modified file in MapleStory local file.

Let's clear up the situation
TKMS (MapleStory Test Server) cannot be opened

All files can be opened in KMS local files.
Save the file to a location other than MapleStory's local file 
I can't open the file can't edit neither apply

hold the save file
even if you run the game
The save file is treated as missing and the game continues.

![image](https://user-images.githubusercontent.com/95957902/147584848-41daebc3-5513-49b0-a0f0-16bd3f3c3a99.png)

**Comment by lastbattle** [comment]
Yes, it needs to be saved under "Maple\Data" for HaRepacker to recognise that it is a 64-bit client WZ and load it as such. I've yet to find a better way of identifying it, as I have to support older versions of WZ files too.

As for the game not loading the saved file, I'll continue looking into it. I suspect that it might be with the offset data for the WZ image.

**Comment by emmez** [comment]
After saving it, the image offset becomes 0bytes.
Is there any special way to do it?

Thank you for your hard work.

**Comment by stillLanze** [comment]
12/30 359patch
TKMS  The patch that came
KMS 359 patch can be opened
as I said too
MapleStory cannot be opened anywhere other than a local file.
Edit a file in a local file
Even if you save and run it, the file is missing and it runs.

take it easy  slowly  as the time comes 
fix it ㅠㅠ
Thank you for your hard work.

**Comment by stillLanze** [comment]
Hello
You always work hard.

Is KMS solution impossible to make anymore?

You cannot open the Heesang with the KMS file you have received.
+ can't save


let me know the latest
If you come up with a perfect solution, could you give me the file again?


![image](https://user-images.githubusercontent.com/95957902/153744021-bd0628ff-4968-42ad-966e-ba7aa60151b2.png)

**Comment by lastbattle** [comment]
Its fixed here https://github.com/lastbattle/Harepacker-resurrected/commit/60fa3818774125af21dc492553ed1a5a389b451c. 
You'll have to compile it yourself for now as I'll not be making a new release yet.
