### ISSUE TITLE
Image Offset is saved as 0. Is there a solution?

### ISSUE THREAD

**Issue by leesumin1** [lastbattle/Harepacker-resurrected#155]
![offest](https://user-images.githubusercontent.com/67950527/148064068-90b2d0ea-d7ea-4f7d-b317-4e9e7064ea1d.JPG)

Image Offset is saved as 0. Is there a solution?

**Comment by KENNYSOFT** [comment]
NOT this repository. https://github.com/KENNYSOFT/WzComparerR2

**Comment by leesumin1** [comment]
> NOT this repository. https://github.com/KENNYSOFT/WzComparerR2

I saved it as a repacker and compared it to WzComparerR2

**Comment by leesumin1** [comment]
Problem solved.

**Comment by emmez** [comment]
Help me , too ㅠㅠ

**Comment by leesumin1** [comment]
> Help me , too ㅠㅠ

연락처 남기슝

**Comment by lastbattle** [comment]
Its fixed here https://github.com/lastbattle/Harepacker-resurrected/commit/60fa3818774125af21dc492553ed1a5a389b451c. 
You'll have to compile it yourself for now as I'll not be making a new release yet.
