### ISSUE TITLE
Damage when saving KMS clients.

### ISSUE THREAD

**Issue by xxxdecode** [lastbattle/Harepacker-resurrected#156]
Is it just me?

**Comment by leesumin1** [comment]
me too

**Comment by xxxdecode** [comment]
I solved it. Liberation from hell.

**Comment by uper1126** [comment]
> 나는 그것을 해결했다. 지옥에서 해방.
Please let me know. how to solve it.
help plz
my discord : lharo#2974

**Comment by leesumin1** [comment]
Help me ㅠㅠ

**Comment by Kajiyaa** [comment]
> I solved it. Liberation from hell.

how'd you fix it?

**Comment by stillLanze** [comment]
> 나는 그것을 해결했다. 지옥에서 해방.

let me know too
How to solve

I can't even open KMS files in the first place

**Comment by leesumin1** [comment]
> > 나는 그것을 해결했다. 지옥에서 해방.
> 
> let me know too How to solve
> 
> I can't even open KMS files in the first place

연락처 남기숑

**Comment by lastbattle** [comment]
latest KMS update broke it again

**Comment by lastbattle** [comment]
Fixed
https://github.com/lastbattle/Harepacker-resurrected/pull/161/commits/1e8bb6374a99880700a71a6fc670a5da467c29c2

**Comment by Hiiih1** [comment]
> > > 나는 그것을 해결했다. 지옥에서 해방.
> > 
> > 
> > 해결 방법도 알려주세요.
> > KMS 파일을 처음부터 열 수도 없습니다.
> 
> 연락처 남기숑

선생님 저도 오프셋 0 저장되는거 해결법좀요..ㅠㅠ

**Comment by Hiiih1** [comment]
> 

THX <3
