### ISSUE TITLE
GMS v.230 wz encoding changed?

### ISSUE THREAD

**Issue by zealop** [lastbattle/Harepacker-resurrected#157]
Seems like they changed the wz encoding when patch v.230 hit, anybody manage to bruteforce it yet?

**Comment by belmont112** [comment]
seems like the same issues kms players had 2-3 months ago.

**Comment by darrenbaha** [comment]
Hi,

How to Fix : 

The key was not changed. 
Nexon removed two bytes that are used for HeaderVersion. 
The fixed Header Version is 777

Also, when saving the WZ files. Where the header starts is no longer decimal 62. It is decimal 60, so you need to remove the +2 from the Header.FStart in the save function. 

Then you should be able to read GMS V230. 

Credits to Elem8100 for the solution.

**Comment by changlinlee** [comment]
@darrenbaha 
Hi darrenbaha,

I'm really interested in your reply, are you using HaRepacker resurrected? 

If yes, could you teach me how to modify the recognized header version number in this software? Cuz I didn't find related option.

If not, please tell me which software are you using,

Thank you so much!

**Comment by zealop** [comment]
Found a temp fix for now
https://forum.ragezone.com/f702/harepacker-v230-fix-1203443/#post9113235
