### ISSUE TITLE
game version error after exporting to PNG

### ISSUE THREAD

**Issue by Kajiyaa** [lastbattle/Harepacker-resurrected#160]
![image](https://user-images.githubusercontent.com/99602728/153758758-443db04a-095b-407c-98d3-a59d6703fd63.png)

at first the program was working just fine, and when I was interested in simply convering the whole "map2" Wz file to png/mp3 it froze half way, probably not the smartest thing on my end but it only converted half of the map objects to PNGs and then froze up on me before force closing, then begun to give me the game version hash error.

wondering if this instance of the error is a new occurance?

**Comment by lastbattle** [comment]
Its fixed here https://github.com/lastbattle/Harepacker-resurrected/commit/60fa3818774125af21dc492553ed1a5a389b451c. 
You'll have to compile it yourself for now as I'll not be making a new release yet.
