### ISSUE TITLE
MSEA v212 error in opening WZ files with harepacker

### ISSUE THREAD

**Issue by tomyummmm** [lastbattle/Harepacker-resurrected#164]
![image](https://user-images.githubusercontent.com/65211592/156314837-0ab90030-c74a-4c46-83fa-bb655630f9b8.png)

Hi, this is new error after patching to newest version, is it possible to fix this?

**Comment by lastbattle** [comment]
Its fixed here https://github.com/lastbattle/Harepacker-resurrected/commit/60fa3818774125af21dc492553ed1a5a389b451c. 
You'll have to compile it yourself for now as I'll not be making a new release yet.
