### ISSUE TITLE
Not working for v83 files (private server)

### ISSUE THREAD

**Issue by Corpse213** [lastbattle/Harepacker-resurrected#170]
Hi,
I'm trying to pull some info from the skill.wz for a v83 private server and all I'm getting is:
![image](https://user-images.githubusercontent.com/101439086/157999759-73fa9ba8-aab3-4a58-9da0-fb592bb2fb51.png)

I've tried gms old, gms, etc, and none of them work.

I tried the bruteforce option but that gets stuck at about 1,000,000 tries.

Am I the only one with this issue?

Thanks.

**Comment by Gabsys** [comment]
It won't work if you are trying to open .wz files of a well-established / slightly smart private server. They would have custom encrypted the .wz files & using this repacker wont decrypt it. This repacker can only be used for the original v83 .wz files

**Comment by Corpse213** [comment]
> It won't work if you are trying to open .wz files of a well-established / slightly smart private server. They would have custom encrypted the .wz files & using this repacker wont decrypt it. This repacker can only be used for the original v83 .wz files

Okay thanks for your reply :)

**Comment by Lesteriax** [comment]
@Gabsys, what about the error saying: Error initializing <file>.wz (error with game version hash : The specified game version is incorrect and WzLib was unable to determine the version itself.
![image](https://user-images.githubusercontent.com/95050087/165849692-2f856b3d-32af-43c3-9f92-3cc7f8aea2e5.png)
