### ISSUE TITLE
导出为XML或者IMG时排序问题

### ISSUE THREAD

**Issue by beloved26** [lastbattle/Harepacker-resurrected#173]
如果有手动添加节点如：动画帧技能等子节点时：
在导出成到出成IMG或者服务端XML会出现乱序，如下：
/**
canvas name="1"/
canvas name="2"/
canvas name="6"/
canvas name="7"/
canvas name="3"/
canvas name="4"/
canvas name="5"/
*/
这会导致客户端在遍历播放动画帧时出现鬼畜行为（乱序）。
请在导出XML或IMG，保存WZ时将节点进行一次排序

**Comment by beloved26** [comment]
![image](https://user-images.githubusercontent.com/45865350/162583773-7bda4c87-1a7d-4f34-a0bc-81ae3d937861.png)

**Comment by Arnuh** [comment]
Order matters a lot and shouldn't be forced by the tool, an option when importing is perfectly fine tho.

Also I think maplelib in general has issues with keeping order when loading&saving data and should be looked into. Obvious case is footholds being moved around despite not changing them.

**Comment by lastbattle** [comment]
Got it, canvas nodes will be sorted as they're saved.
