### ISSUE TITLE
New MSEA patch v213 New WZ file structure

### ISSUE THREAD

**Issue by tomyummmm** [lastbattle/Harepacker-resurrected#174]
![image](https://user-images.githubusercontent.com/65211592/163146111-7e144c8c-7c9c-41c9-8704-8e3f11c7354b.png)

![image](https://user-images.githubusercontent.com/65211592/163146002-580782ad-d4d3-4667-9331-f187f95e2b94.png)
![image](https://user-images.githubusercontent.com/65211592/163146014-0b47be64-7513-465f-a147-31b0a802ee79.png)

Unable to open any wz file.

This is using the latest commit and build.

**Comment by tomyummmm** [comment]
Strangely your last release of version 4.3 works on the .wz files, will use that version for now.

**Comment by zsphuah** [comment]
does wz editing still working in msea? My client closes after skill.wz editing

**Comment by lastbattle** [comment]
Its supported in the latest version.
