### ISSUE TITLE
Failed to parse wz on 'staging' branch

### ISSUE THREAD

**Issue by toyobayashi** [lastbattle/Harepacker-resurrected#175]
Client: GMS 231.1
WZ file: Sound.wz, Sound2.wz etc

I could open wz file in GUI but could not expand it... While master branch is all ok

![image](https://user-images.githubusercontent.com/23353576/164014501-e7fc03c8-55a6-48f0-86b9-ef47d44c83e9.png)

![image](https://user-images.githubusercontent.com/23353576/164014780-abb159a2-7507-412a-8a02-461667330712.png)

Failed to parse but returned `WzFileParseStatus.Success` in `ParseMainWzDirectory` 

Is this a bug?

**Comment by toyobayashi** [comment]
Then I tried to change the code like this, fixed! I don't know whether it is correct

![image](https://user-images.githubusercontent.com/23353576/164017432-cc2676e9-a561-4f9e-9924-6737ddcfca39.png)

**Comment by lastbattle** [comment]
It is still being worked on. I will have an official release by the end of this year.
