### ISSUE TITLE
HaRepacker & Creator not working on V230

### ISSUE THREAD

**Issue by closewall** [lastbattle/Harepacker-resurrected#176]
HaRepacker no longer works with the latest version, and returns this error message when you try to open a .wz file:

`Error initializing Mob.wz (Error with game version hash : The specified game version is incorrect and WzLib was unable to determine the version itself).`

Baha on ragezone released a fix, and detailed the changes required to fix the issue, but in his release, HaCreator does not work. It simply will not start.

https://forum.ragezone.com/f702/harepacker-v230-fix-1203443/

**Comment by lastbattle** [comment]
Yea, this is already implemented. Nexon changed them yet again, I dont have time to work on it at the moment.
Closed, duplicate issue.
