### ISSUE TITLE
Error Initializing <file>.wz

### ISSUE THREAD

**Issue by Lesteriax** [lastbattle/Harepacker-resurrected#177]
I'm getting the following:

Error initializing <file>.wz (error with game version hash : The specified game version is incorrect and WzLib was unable to determine the version itself.
![image](https://user-images.githubusercontent.com/95050087/165849692-2f856b3d-32af-43c3-9f92-3cc7f8aea2e5.png)

Any solution to this? What could be causing it? I was able to open the file in an older viewer (Not editor) but could not on harepacker

**Comment by ShowerLee69** [comment]
Same question, have you solved it?

**Comment by PirateIzzy** [comment]
Been having this issue with the latest GMS patch as well.

**Comment by Lesteriax** [comment]
@ShowerLee69, I was able to, but I was editing an older version, not the current gms. Add me if you want to discuss more House#4086

**Comment by lastbattle** [comment]
Its fixed in the latest version, get it here:
https://github.com/lastbattle/Harepacker-resurrected/releases/tag/5.0
