### ISSUE TITLE
[HaCreator] can't even start

### ISSUE THREAD

**Issue by terjun** [lastbattle/Harepacker-resurrected#179]
I use a translator because my English is not good, so the sentences may be weird.
Simply put, I can't even start.

I have KMST 1.2.138 ver end GMS 232.1 ver
GMS files are scheduled to be updated.

I tried Encryption with each client, but unfortunately it didn't work.
Even worse, the cause is don't know.

Anybody please help me.
I will write the Discord separately upon request.

And another story, I can't open GMS WZ files in Harepacker.

![aaaaaaaaaaaaaaaaaaa](https://user-images.githubusercontent.com/107240786/173011922-e87fbc07-cc8a-4843-b191-008714353c8c.png)

**Comment by terjun** [comment]
GMS also now has a 64-bit client patched so the files are split.
GMS version is now 233.1.

**Comment by SoulGirlJP** [comment]
I didn't even finish to implement the 64 bit HaRepacker as i never continued to do so really, ill have to update it and do some modifications to it.

**Comment by Alon-Sachs** [comment]
> I didn't even finish to implement the 64 bit HaCreator as i never continued to do so really, ill have to update it and do some modifications to it.

Any news about the update? tbh no other source of such tool so you are our only hope 😂

**Comment by lastbattle** [comment]
Its supported in the latest version.
