### ISSUE TITLE
[HaRepacker]  Is it normal for the green status bar to stay green after exporting?

### ISSUE THREAD

**Issue by cnguye** [lastbattle/Harepacker-resurrected#181]
Hello,

First time with .NET, MS Visual Studio, and HaRepacker (I'm surprised I got it to build successfully)

Every time I export Selection > to XML > Classic/PS, the status bar looks like it's hanging(?). Nothing else happens and I am able to use the application as normal.  Is this normal behavior?  Should there be a notification that the export was successful?  Image below is what I see as long as I am on the same instance of the app.

![image](https://user-images.githubusercontent.com/22929438/182915989-7f9b1009-b9c0-43b0-ac36-58acd86d7ac0.png)

I ask because I am trying to make a custom NPC, but nothing happens every time I try to import a classic xml right after exporting it.  It seems like I'm trying to import an existing node so it just overwrites or doesn't get added.

Thank You

**Comment by RangFarm** [comment]
x

**Comment by lastbattle** [comment]
Yes, looks like it is done exporting.
