### ISSUE TITLE
Cannot open v83 maps in HaCreator

### ISSUE THREAD

**Issue by Souna** [lastbattle/Harepacker-resurrected#186]
Hello,

Attempting to open v83 maps in HaCreator does not work. The selector simply shows  "Map does not actually exist" for all maps except MapLogin and CashShopPreview. Why is this?

For encryption I am selecting GMS, just as I did for the old version of HaCreator.

![image](https://user-images.githubusercontent.com/8890024/205479675-15cc3ac7-2e5a-4dcb-909c-058131d162ce.png)

**Comment by lastbattle** [comment]
Wait for the next release, I've just tested that against v83.

https://github.com/lastbattle/Harepacker-resurrected/commit/f40773a3333e3c34381d65175ed609110d560274
