### ISSUE TITLE
Error trying to overwrite WZ file

### ISSUE THREAD

**Issue by tomyummmm** [lastbattle/Harepacker-resurrected#191]
![image](https://user-images.githubusercontent.com/65211592/209676790-19a11a45-b5ea-4752-9c1f-38bcc57dc152.png)

When opening the WZ file, changing, and over-writing in the same folder, throws an error. Using the latest 5.0 version.

Does not show option to rename the file instead, just leaves the tmp file in the folder. no indication if the changes were made to the file? referencing commit #148

**Comment by UltimateMors** [comment]
You have to save it as a new file.

Saving all together is quite busted on this version, unfortunately.

**Comment by tomyummmm** [comment]
Yes, thats what i did. But based on the referenced commit, previous versions merely overwrite without throwing exceptions.

**Comment by Myst123Myst** [comment]
How do you save it as a new file? I don't know how to do that. I'm getting the same error where it throws an error trying to over-write wz.

**Comment by tomyummmm** [comment]
> How do you save it as a new file? I don't know how to do that. I'm getting the same error where it throws an error trying to over-write wz.

Just save with a different file name and swap it.

**Comment by lastbattle** [comment]
Fixed in the latest version.

https://github.com/lastbattle/Harepacker-resurrected/releases/tag/5.1
