### ISSUE TITLE
Analyze Error

### ISSUE THREAD

**Issue by v3921358** [lastbattle/Harepacker-resurrected#204]
There will be no image in Morph.wz (TMS118) because the wrong version has passed the versionHash check.
BTW. 
The situation is the same with KMS779-Weapon003

Additionally, it can't open the wz file 'Skill.wz' in TMS113. 

These conditions make it unable to analyze

if (mapleStoryPatchVersion == 113) {
    // hack for now
    reader.BaseStream.Position = fallbackOffsetPosition; // reset
    return false;
}

And here are the wz file and exe:

https://mega.nz/folder/6QgCTa7b#eJs07rzEdmtNE-wgtc9NOg

**Comment by lastbattle** [comment]
Fixed, feel free to compile a version yourself for now until the next release.
