### ISSUE TITLE
Fix linked image for old MapleStory ver. (Request to remove all _hash nodes)

### ISSUE THREAD

**Issue by tifa-l** [lastbattle/Harepacker-resurrected#211]
When I use that button, it removes the _hash nodes superficially, but once I save it, the _hash nodes are still in the files. 
Before:
![image](https://github.com/lastbattle/Harepacker-resurrected/assets/132535797/edd3d3bf-6b50-4d9e-aaea-5e227f0c2b62)
After:
![image](https://github.com/lastbattle/Harepacker-resurrected/assets/132535797/f7c96ddb-9abb-408d-aab3-0bc782af7553)

But upon saving the .wz file, the _hash nodes have not actually been removed upon checking the files. 
Could you make it so that it removes the _hash nodes when pressing "Fix linked image for old MapleStory ver." please? 

Would be very helpful to reduce the file sizes! Thanks!

**Comment by lastbattle** [comment]
https://github.com/lastbattle/Harepacker-resurrected/commit/af6ad0a322663c78b579bc1aaa8da411ed74d850
