### ISSUE TITLE
Forced sorting on save breaks wz files

### ISSUE THREAD

**Issue by Arnuh** [lastbattle/Harepacker-resurrected#217]
I already stated this in the initial issue #173 that ended up introducing such change. This change directly breaks wz files.

Running something as simple as what's shown below "corrupts" Base.wz due to the code introduced in https://github.com/lastbattle/Harepacker-resurrected/commit/a5760d43eb187354c466665a404ee5ca9f3e2001
```
private static void PrepareAllImages(WzDirectory dir) {
    foreach (WzImage img in dir.WzImages) {
        img.ParseImage();
        img.Changed = true;
    }

    foreach (WzDirectory subDir in dir.WzDirectories) {
        PrepareAllImages(subDir);
    }
}

static void modifyBase(WzMapleVersion version) {
    WzFile wzFile = new WzFile(Path.Combine(baseDir, "Base.wz"), version);
    wzFile.ParseWzFile();
    
    PrepareAllImages(wzFile.WzDirectory);
    
    wzFile.SaveToDisk(Path.Combine(outputDir, "Base.wz"), false, version);
}
```

I suggest reverting the commit and looking to introduce the feature in another manner if still deemed as needed.

Order matters, MapleLib should never touch it without the user opting in. Attempting to add workarounds where ever it breaks things is not the correct way.

![proof](https://github.com/lastbattle/Harepacker-resurrected/assets/2877803/e6e9b708-daee-4b55-b34d-90bb489516e8)

**Comment by lastbattle** [comment]
It's always hard to catch issues like this, given the enormous amount of versions and variations of files to be tested against.
I wish it could be done automatically someway, somehow.

**Comment by lastbattle** [comment]
Perhaps limiting the sorting to only map layer canvas and subproperty?

**Comment by Arnuh** [comment]
Like I said previously, sorting shouldn't happen unless its opt in.

I'd assume proper setup is the following, hopefully I'm not missing anything.
1. Import should obviously keep the exact order being imported, appending to bottom of any previous data if such exists.
2. Manual property creation should just append to the bottom like 1.
3. Give a right click option on WzFile, WzImage, and WzDirectory, or all to sort the sub properties
4. No forced sorting anywhere :) A complete load of the wz & then full save should give an identical wz back.

**Comment by lastbattle** [comment]
![image](https://github.com/lastbattle/Harepacker-resurrected/assets/4586194/4c9eaf7e-6975-4de6-a8fb-916375dad77c)

**Comment by Arnuh** [comment]
I'll close it. From my basic usage it seems to work as intended, any issues with the sort buttons would be a new issue imo.

**Comment by wangxiaobao0851** [comment]
![image](https://github.com/lastbattle/Harepacker-resurrected/assets/142079448/5fb1e33b-7f09-4607-b43f-e92816a6780b)
Your problem also occurred when I saved GMSv83 as another IV. How did you solve it? Can you guide me to solve it? Is there a bug in the operation or can you post the code that fixes the problem.

**Comment by Arnuh** [comment]
> ![image](https://private-user-images.githubusercontent.com/142079448/293362794-5fb1e33b-7f09-4607-b43f-e92816a6780b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4OTk4NDcsIm5iZiI6MTcwMzg5OTU0NywicGF0aCI6Ii8xNDIwNzk0NDgvMjkzMzYyNzk0LTVmYjFlMzNiLTdmMDktNDYwNy1iNDNmLWU5MjgxNmE2NzgwYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjMxMjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIzMFQwMTI1NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNDRlMmRiYTRmZjVhOWFiNjIzNmIyYTIxOWQ1MGVmYzM4NGRhYTEzY2MwYmY1ZjM2OTU4MzZkZmI5ZDlmZmRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KkGqChuHnM5b29ZoCzGK7ZI0vohG1FJ__k-LMwiS8yA) Your problem also occurred when I saved GMSv83 as another IV. How did you solve it? Can you guide me to solve it? Is there a bug in the operation or can you post the code that fixes the problem.

Latest release doesn't have the issue fixed, you have to build it yourself for now if you want it fixed.
