### ISSUE TITLE
some source files missing! StatusBarUI.cs and MinimapUI.cs

### ISSUE THREAD

**Issue by SourDumplings** [lastbattle/Harepacker-resurrected#229]
My Visual studio complains:
8>CSC : error CS2001: Source file 'E:\Github\Harepacker-resurrected\HaCreator\MapSimulator\MapObjects\UIObject\StatusBarUI.cs' could not be found.
8>CSC : error CS2001: Source file 'E:\Github\Harepacker-resurrected\HaCreator\MapSimulator\MapObjects\UIObject\MinimapUI.cs' could not be found.

**Comment by lastbattle** [comment]
I'll resolve it in a bit by committing the bits, been working on something else.

**Comment by drone0898** [comment]
checkout this version of commit.

it works

[416de8e6c7926ff779abb20fdb7099ad84a8ffeb version commit]
(https://github.com/lastbattle/Harepacker-resurrected/commit/416de8e6c7926ff779abb20fdb7099ad84a8ffeb)

**Comment by lastbattle** [comment]
The staging version works for now.

I was still in the process of implementing a framework for UI but was not completed yet so.. will do it soon. 
![image](https://github.com/lastbattle/Harepacker-resurrected/assets/4586194/bd5ef078-6b30-41f0-8019-0d52e7dbd3f9)

**Comment by lastbattle** [comment]
StatusBarUI.cs and MinimapUI.cs is in the latest commit.
