### ISSUE TITLE
Objects don't save as flipped on minimap

### ISSUE THREAD

**Issue by voleth** [lastbattle/Harepacker-resurrected#249]
Objects that are "Flipped" don't save that way on the minimap. This has been a thing since the creation of HaCreator. lol

![Screenshot 2024-08-11 024104](https://github.com/user-attachments/assets/3b7ec862-519d-4498-95dd-2ee51f02bd98)

**Comment by lastbattle** [comment]
Fixed, you'll have to compile it yourself for now or alternatively wait for the next release.
