### ISSUE TITLE
HaCreator Problem (Latest commit)

### ISSUE THREAD

**Issue by s-channarit** [lastbattle/Harepacker-resurrected#25]
![image](https://user-images.githubusercontent.com/2369437/80311287-0220ab00-8809-11ea-8c4c-25aedb3df759.png)

I got an error like this.

**Comment by lastbattle** [comment]
it isnt compatible to the latest ver of maplestory as of yet, tested on just < 150 (somewhere around chaos, and ascension)

**Comment by s-channarit** [comment]
I test on bigbang version - ems (old), Maybe I will try tp fix it by myself first.

Regards.

**Comment by s-channarit** [comment]
@lastbattle I found it!. If I use "Auto Detected" I will found error but If I change to MSEA EMS. It will ok.

Regards

**Comment by lastbattle** [comment]
great if that works!
