### ISSUE TITLE
Any plan to upgrade to the latest dotnet version? e.g. net 8?

### ISSUE THREAD

**Issue by genment** [lastbattle/Harepacker-resurrected#258]
I would like to submit a PR for this upgrade. Would you be open to merging it?

I have made the upgrade on my repo and it works great!

**Pros:**
1. Significantly improved performance
2. Modern language/framework features

**Cons:**
1. Few API changed/removed
1. Increased release file size (publish with self-contained framework option)

**Comment by lastbattle** [comment]
Yes, it's in my TODO list too but it's just a little too tedious for me until existing issues that are prioritized are resolved.
I would be happy to work on that with you, if you are interested.

**Comment by lastbattle** [comment]
Are you using the automated tool by any chance? I've heard of it a while ago, but I have not tried them. 
https://learn.microsoft.com/en-us/dotnet/core/porting/upgrade-assistant-overview

**Comment by lastbattle** [comment]
I'm attempting it right now, all good thus far! Will push it as soon as I can. 

https://github.com/lastbattle/MapleLib
https://github.com/lastbattle/dockpanelsuiteCore

**Comment by lastbattle** [comment]
HaCreator works now, aside from bitmap issues with images being cut off. investigating.
https://github.com/lastbattle/Harepacker-resurrected/commit/114579e72fb44a74db176ef49c47cb8b86344a2c
https://github.com/lastbattle/Harepacker-resurrected/commit/9813e8e30f093a4f75e55a562f538d0bf43ca8c8

-DPI awareness:
-GDI+ vs. WIC:
-Memory management:

![image](https://github.com/user-attachments/assets/d05346de-d7bd-442d-b5f4-d0ff1dea71ce)

**Comment by genment** [comment]
Yes, I used the upgrade assistant and made some manual fixes.

It took me hours to identify the cause of the image cut-off issue, which was due to a breaking change in the behavior of DeflateStream since .NET 6.
[6ad974ee92192786c789211fb5319fc34ee610dd](https://github.com/genment/MapleLib4HarepackeR/commit/6ad974ee92192786c789211fb5319fc34ee610dd)

**Comment by genment** [comment]
**Friendly reminder:** It seems like the entire codebase was replaced during this upgrade, which has resulted in the loss of all previous Git tracking history for every code file. In reality, upgrading to .NET Core typically only changes the `.csproj` project files, as the upgrade assistant handles this with the `in-place` option. All C# code files should remain unchanged, with possibly just a few manual fixes if needed.

It's totally fine if you wanted a fresh codebase, though 😄

**Comment by lastbattle** [comment]
I thought of just keeping it as another fork named "net 4.8.1" for archival purposes, but it's alright as I've already overwritten it. 😆

**Comment by genment** [comment]
After giving it some more thought, I would like to suggest reconsidering the approach. 😅

Would you mind creating a new "staging" branch from the commit just before the upgrade and starting the upgrade process again, but this time using the "in-place" option?

I believe keeping the file history is really important, especially when it comes to debugging. Git commit messages can provide valuable context for understanding why certain changes were made.

**Comment by genment** [comment]
here are some upgrading tips:
1. use `<TargetFramework>net8.0-windows</TargetFramework>` for all dotnet projects
2. set `<GenerateAssemblyInfo>true</GenerateAssemblyInfo>` for all dotnet projects
  - this will suppress all platform specific warning when building projects, [ref 1](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1416#tfm-target-platforms), [ref 2](https://stackoverflow.com/questions/10311347/duplicate-assemblyversion-attribute)

**Comment by lastbattle** [comment]
All done in both MapleLib and HaRepacker! Awesome!! 

https://github.com/lastbattle/Harepacker-resurrected/commit/f9f167f1ecbd4bdb92d9251962580817e8b04a2b
https://github.com/lastbattle/MapleLib/commit/900e2b016313fd225f017707ffa276f6f5c9417b

**Comment by lastbattle** [comment]
> Yes, I used the upgrade assistant and made some manual fixes.
> 
> It took me hours to identify the cause of the image cut-off issue, which was due to a breaking change in the behavior of DeflateStream since .NET 6. [6ad974ee92192786c789211fb5319fc34ee610dd](https://github.com/genment/MapleLib4HarepackeR/commit/6ad974ee92192786c789211fb5319fc34ee610dd)

Would you mind creating a pull request for this?

**Comment by genment** [comment]
Cool! Thanks for taking my suggustion!!

> > Yes, I used the upgrade assistant and made some manual fixes.
> > It took me hours to identify the cause of the image cut-off issue, which was due to a breaking change in the behavior of DeflateStream since .NET 6. [6ad974ee92192786c789211fb5319fc34ee610dd](https://github.com/genment/MapleLib4HarepackeR/commit/6ad974ee92192786c789211fb5319fc34ee610dd)
> 
> Would you mind creating a pull request for this?

Sure, just give me a minute.
