### ISSUE TITLE
Having issues releasing as x86

### ISSUE THREAD

**Issue by sirdanielot** [lastbattle/Harepacker-resurrected#270]
Using Visual Studio 2022, the project will only build using the "Any CPU" option, and the folders that have been built don't match that of the release script.

Could you please confirm how I can build an x86 version of this?

I am attempting to export .img files for x86 and this is failing using the any CPU Exe.

**Comment by lastbattle** [comment]
```
<?xml version="1.0" encoding="utf-8"?>
<!--
https://go.microsoft.com/fwlink/?LinkID=208121.
-->
<Project>
  <PropertyGroup>
    <Configuration>Release</Configuration>
    <Platform>Any CPU</Platform>
    <PublishDir>bin\Release\net8.0-windows\publish\win-x64\</PublishDir>
    <PublishProtocol>FileSystem</PublishProtocol>
    <_TargetId>Folder</_TargetId>
    <TargetFramework>net8.0-windows</TargetFramework>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishReadyToRun>true</PublishReadyToRun>
    <!-- AOT and Trimming Configuration -->
    <PublishAot>false</PublishAot>
    <_SuppressWinFormsTrimError>true</_SuppressWinFormsTrimError>
    <_SuppressWpfTrimError>true</_SuppressWpfTrimError>
  </PropertyGroup>
</Project>
```

This is what the FolderProfile.pubxml looks like under 'HaRepacker\Properties\PublishProfiles'.

**Comment by sirdanielot** [comment]
Okay thank you, got that working. Out of curiosity why would a configuration like this not be included?

**Comment by lastbattle** [comment]
I'll include it, I guess the default .gitignore for VisualStudio excluded that.

**Comment by lastbattle** [comment]
https://github.com/lastbattle/Harepacker-resurrected/commit/58dc5a272425d59407f595033b7c5c08aed80e02
Fixed.
