### ISSUE TITLE
Issue with Saving String.wz or Quest.wz in HaCreator.exe: Corrupted Images Due to Long Strings

### ISSUE THREAD

**Issue by as121255** [lastbattle/Harepacker-resurrected#273]
My question: After editing a map using HaCreator.exe, saving String.wz or Quest.wz causes the images (img) inside the WZ file to become corrupted. The reason might be that the string is too long, causing the save operation to fail. Please see the image!
![图2](https://github.com/user-attachments/assets/ae2b772d-c2f9-490d-84a5-c9deb7821b60)
![图3](https://github.com/user-attachments/assets/10174bf9-442a-4b12-83c4-c2239418910f)

**Comment by lastbattle** [comment]
Could you give me the exact MapleStory version that you are using?

**Comment by as121255** [comment]
> 您能告诉我您使用的 MapleStory 的确切版本和本地化版本吗？

The translation would be: "Using version 7.1 of HaCreator, locally MapleStory GMS083."

**Comment by lastbattle** [comment]
All resolved, you might want to recompile a version of the **staging** branch. 
https://github.com/lastbattle/Harepacker-resurrected/tree/staging

**Comment by lastbattle** [comment]
https://github.com/lastbattle/Harepacker-resurrected/releases/tag/7.1.1
