### ISSUE TITLE
No EMS options when choosing version

### ISSUE THREAD

**Issue by Fraysa** [lastbattle/Harepacker-resurrected#28]
I'm currently working on a v.76 EMS application (GMS v.95 equivalent). Using the drop down menu, what works for this version is MSEA/Taiwan (old).

EMS (old) should be added as well to avoid confusion.

Also, why not just let the program guess the version? I'm not too familiar with WZ files as I'm only coding server things - but I guess the file header should tell you which version it is?

**Comment by lastbattle** [comment]
I'll add EMS to that drop-down too! 
Yeah, I kinda suspect that both EMS and MSEA is really just a single development team and it make sense that it shares the same key. 

![1](https://user-images.githubusercontent.com/4586194/80517626-f0313a80-89b7-11ea-9e97-d659f258ce4f.PNG)
I saw many hints of that in the MSEA client, including a full-working EMS launcher that can be enabled by just changing an instruction during startup.. 


As for the detection of keys, I dont think it is feasible as it will take far too much time to load the latest version of MapleStory (v180++). 

Here's why: 
`        internal bool ParseMainWzDirectory(out string parseErrorMessage, bool lazyParse = false)
        {
            if (this.path == null)
            {
                Helpers.ErrorLogger.Log(Helpers.ErrorLevel.Critical, "[Error] Path is null");
                parseErrorMessage = "[Error] Path is null";
                return false;
            }
            WzBinaryReader reader = new WzBinaryReader(File.Open(this.path, FileMode.Open, FileAccess.Read, FileShare.Read), WzIv);

            this.Header = new WzHeader();
            this.Header.Ident = reader.ReadString(4);
            this.Header.FSize = reader.ReadUInt64();
            this.Header.FStart = reader.ReadUInt32();
            this.Header.Copyright = reader.ReadNullTerminatedString();
            reader.ReadBytes((int)(Header.FStart - reader.BaseStream.Position));
            reader.Header = this.Header;
            this.version = reader.ReadInt16();

            if (mapleStoryPatchVersion == -1)
            {
                const short MAX_PATCH_VERSION = 10000; // wont be reached for the forseeable future.

                for (int j = 0; j < MAX_PATCH_VERSION; j++)
                {
                    this.mapleStoryPatchVersion = (short)j;
                    this.versionHash = GetVersionHash(version, mapleStoryPatchVersion);
                    if (this.versionHash == 0)
                    {
                        continue;
                    }`

**Comment by Fraysa** [comment]
Thanks for your input. I'm closing the issue. I sent you a message on Twitter regarding this project, please add me on Discord instead if you prefer: Fraysa#2832.
