### ISSUE TITLE
Unknown property type at ParsePropertyList, ptype = x

### ISSUE THREAD

**Issue by MedicOP** [lastbattle/Harepacker-resurrected#29]
I keep running into this error when opening certain IMGs:
`Unknown property type at ParsePropertyList, ptype = (insert number here)` 

For example, I get the number ptype = 184 when opening clean v83 Item.wz > Etc > 0400.img

However, the same error does not occur when I try open that node using the old HaRepacker 4.2.4

**Comment by MedicOP** [comment]
Nevermind, it only seems to happen when I build the latest source as of writing. It does not happen on the latet released version

**Comment by lastbattle** [comment]
Almost missed this!

Thanks for the heads up, its fixed here. 
https://github.com/lastbattle/Harepacker-resurrected/commit/8be7e79c001f5e347e1adc378159ab668e7e9b21
