### ISSUE TITLE
"The given path's format is not supported"

### ISSUE THREAD

**Issue by Hyoretsu** [lastbattle/Harepacker-resurrected#31]
When trying to extract UI.wz/AllianceUI.img/ChallengeUI/button:help I get [the following error log](https://pastebin.com/CPax9uMW). Note that : is a forbidden character in Windows \ / : * ? " < > | (I also get that on GuildUI and FarmUI, basically anywhere that has said character), I am using latest release.

On a side note I also get [this error](https://pastebin.com/9TVTGiiv) sometimes: (Tried to extract Charater.wz)
Unable to cast object of type 'System.Object[]' to type 'System.Int32[]'.

**Comment by lastbattle** [comment]
![x](https://user-images.githubusercontent.com/4586194/81262372-53823300-9070-11ea-90eb-8e2428587eb0.PNG)

fixed, you'll have to compile it yourself for the time being.

https://github.com/lastbattle/Harepacker-resurrected/commit/58fb304b3dddd66c45974182aee1f8b694535d40

**Comment by Hyoretsu** [comment]
K, that isue's solved, do I just close it and you can mark it as solved later on?

Also, not that big of an issue but still a bug nonetheless, that Unable to cast object of type 'System.Object[]' to type 'System.Int32[]'. happens when you try to extract a whole .wz file. I managed to fully extract UI.wz using selection export, but when I tried to extract it as a file it threw that.

**Comment by lastbattle** [comment]
I'll close it
