### ISSUE TITLE
Clipped images in UI.wz

### ISSUE THREAD

**Issue by nqcuong2** [lastbattle/Harepacker-resurrected#38]
https://github.com/lastbattle/Harepacker-resurrected/commit/27740271fd9875a5704b0a4952abc25d3c7c0bef

Something changed in the above commit makes the images in UI.wz file such as images in StatusBar3 in the attached pictures.

https://imgur.com/a/znxLeMi

**Comment by lastbattle** [comment]
Tested as of 07/03/2020. Its fixed in the latest commit.
