### ISSUE TITLE
New Map.wz -> Map002.wz

### ISSUE THREAD

**Issue by CohortMinseok** [lastbattle/Harepacker-resurrected#40]
Would you be able to fix the map rendering for the new Map WZ files? Looks like all the maps are now being placed into the Map002.wz for the newer gMS versions. Also, for some reason after editing any of the maps creates an error -> buffer cannot be null.

**Comment by lastbattle** [comment]
Hacreator for the latest ver is still a work in progress. You will have to compile it yourself if you have to test it right now. /staging

If you encounter any issues, feel free to raise an issue again with specific detail.

**Comment by CohortMinseok** [comment]
This is for HaRepacker. You're not able to render maps with the new formats they are using.
