### ISSUE TITLE
Object reference not set to an instance of an object (HaCreator)

### ISSUE THREAD

**Issue by fahmi1999** [lastbattle/Harepacker-resurrected#42]
This error pops out when I attempt to save the wz & repack the map.wz 
![image](https://user-images.githubusercontent.com/64059914/83113763-a9d81400-a0fa-11ea-8605-42def6f5690f.png)

from the errors.txt
> Starting error log on 28/5/2020 12:00:00 AM
> IncorrectStructure: [ExtractSoundFile] Error parsing sound, BgmTW.img file.
> Error: System.InvalidCastException: Unable to cast object of type 'MapleLib.WzLib.WzProperties.WzUOLProperty' to type 'MapleLib.WzLib.WzProperties.WzBinaryProperty'.
>    at HaCreator.Wz.WzFileManager.ExtractSoundFile(String soundWzFile) in C:\Users\Fam\Desktop\Harepacker-resurrected\HaCreator\Wz\WzFileManager.cs:line 237
> : 
> [ExtractSoundFile] Error parsing sound, BgmTW.img file.
> Error: System.InvalidCastException: Unable to cast object of type 'MapleLib.WzLib.WzProperties.WzUOLProperty' to type 'MapleLib.WzLib.WzProperties.WzBinaryProperty'.
>    at HaCreator.Wz.WzFileManager.ExtractSoundFile(String soundWzFile) in C:\Users\Fam\Desktop\Harepacker-resurrected\HaCreator\Wz\WzFileManager.cs:line 237

**Comment by bwilmott** [comment]
I'm also having this same issue.

**Comment by lastbattle** [comment]
https://github.com/lastbattle/Harepacker-resurrected/commit/0a2a267d1246aca1fef3b8d0b8655c3e31537bef

Fixed.
