### ISSUE TITLE
v83 request - wz files over 2gig

### ISSUE THREAD

**Issue by resinate** [lastbattle/Harepacker-resurrected#44]
any chance of fixing the bug with creator not able to use map wz over 2 gig.
we got img patch working on v83 so this would help us

**Comment by shavitush** [comment]
It's pointless. PCOM uses signed comparisons when reading from the WZ file.

**Comment by lastbattle** [comment]
👆🏻 above

Yes, no way this can be fixed via the repacker without modifying PCOM.
