### ISSUE TITLE
HaCreator ，Before BB, there will be two serious bugs

### ISSUE THREAD

**Issue by 3420525** [lastbattle/Harepacker-resurrected#70]
The bug is as follows:

1: When using hacreator to save the edited content, the PNG of the mini map will be lost.
2: When using mapsimulation, it crashes.

Both of the above two bugs occur on the client before BB. The client after BB can use mapsimulation, and then there will still be a bug in which the PNG of the mini map is lost. The map cannot be accessed.

**Comment by 3420525** [comment]
In addition, you cannot use mouse scrolling to move the map content you are editing up and down. @lastbattle

**Comment by lastbattle** [comment]
2. Fixed.
https://github.com/lastbattle/Harepacker-resurrected/commit/db5d9c4b1358a677a63425574a5abe9ae5b5ba57

**Comment by lastbattle** [comment]
3. Scrolling with mouse wheel. I made it scroll horizontally instead of vertically as most maps are designed wide than tall.

https://github.com/lastbattle/Harepacker-resurrected/commit/2c7177a3da0927bf63c93a9f030a6c62de578ccb

**Comment by lastbattle** [comment]
As for 1. it seems to be working on my end. 
Have you tried clicking on the 'generate minimap' before attempting to save ?

Perhaps in the future I'll make that automatic.
 
![image](https://user-images.githubusercontent.com/4586194/90639024-b20aa000-e260-11ea-8fd9-8e42e8f89366.png)

**Comment by 3420525** [comment]
Thank you for your reply. I tried to generate a new map, but he will still lose the PNG. I think it may be encrypted.

**Comment by 3420525** [comment]
There is also a problem, not like the first version of hacreator. Drag the doo image directly onto the map simulator.

**Comment by 3420525** [comment]
1: When using hacreator to save the edited content, the PNG of the mini map will be lost.
This problem still exists. I use CMS,

**Comment by 3420525** [comment]
Using harepacker recurrected is the same problem, PNG exception.

**Comment by 3420525** [comment]
@lastbattle When you have time, please fix the bug that PNG lost when hacreator saved the map. This happens on CMS. I did not test GMS. In addition, the PNG will be lost when using harepacker recovered, which should be the same problem.

**Comment by lastbattle** [comment]
I'll look into it when I have some time to spare!

**Comment by lastbattle** [comment]
Fixed. Let me know if its still unresolved.
I'll leave this open for now.

65b07f0
