### ISSUE TITLE
I change the image, open wz again and the image disappears.

### ISSUE THREAD

**Issue by rc0n9027** [lastbattle/Harepacker-resurrected#72]
[
![캡처](https://user-images.githubusercontent.com/54577916/91675445-5fda5080-eb77-11ea-9d51-0ce61b78d303.PNG)
](url)

**Comment by 3420525** [comment]
@lastbattle  他He had the same problem as I did. The picture was lost when the change was saved.  - . -

**Comment by Z41N** [comment]
Still having the same issue where image does not save... blank

**Comment by lastbattle** [comment]
Fixed.
https://github.com/lastbattle/Harepacker-resurrected/commit/65b07f01f618949b9630b7a59f394b0e552d90f5
