### ISSUE TITLE
When you save the map and log in to the game, the game is forcibly ended due to the Minimap.

### ISSUE THREAD

**Issue by rc0n9027** [lastbattle/Harepacker-resurrected#73]
Probably there was an error while creating the minimap.

**Comment by lastbattle** [comment]
It might not necessarily be the minimap, but missing wz values under info/.
There are still some properties that are unsupported in the later ver. of MapleStory.

**Comment by lastbattle** [comment]
Fixed.
https://github.com/lastbattle/Harepacker-resurrected/commit/65b07f01f618949b9630b7a59f394b0e552d90f5
