### ISSUE TITLE
Clean Debug Build Issue

### ISSUE THREAD

**Issue by Z41N** [lastbattle/Harepacker-resurrected#83]
![image](https://user-images.githubusercontent.com/7968059/100520652-d41f9280-316c-11eb-9ef4-4f0141cc1048.png)

**Comment by lastbattle** [comment]
fixed https://github.com/lastbattle/Harepacker-resurrected/commit/8b9eab2a06544c413667cd75f1bdfe16176a44ca

**Comment by Z41N** [comment]
> fixed https://github.com/lastbattle/Harepacker-resurrected/commit/8b9eab2a06544c413667cd75f1bdfe16176a44ca

Confirmed fixed.
New issue added.
