### ISSUE TITLE
Deleting FH's with HaCreator

### ISSUE THREAD

**Issue by bwilmott** [lastbattle/Harepacker-resurrected#94]
If you delete FH's and save the map, it renames the FH's. This might not really be an "issue" for some. But for the purpose I'm using it for, it causes a crash when I load my server.
But if you do it through HaRepacker, it doesn't rename or cause a crash and honestly, that's how I think it should work for HaCreator too.

**Comment by lastbattle** [comment]
You will have to re-export the XMLs from WZ into your server files.

Hope that helps.
