### ISSUE TITLE
Something is wrong with image....

### ISSUE THREAD

**Issue by TokyoSU** [lastbattle/Harepacker-resurrected#96]
something want wrong with the image, it's not related to harepacker but to maplelib since i load it with maplelib (from this repo) and only with logo.img (nexon/wizet): 
https://i.imgur.com/jzHwOg9.png
it work fine with the HaSuite-211 through :x
using v83 or latest version from steam, it's the same issues

**Comment by lastbattle** [comment]
Fixed. You might have to compile a copy yourself, as I am not making a release any time soon. 

https://github.com/lastbattle/Harepacker-resurrected/commits/master

**Comment by TokyoSU** [comment]
Thank you, i will compile it myself, no problem :)
